name: skor_id_flutter
description: Swipe Read Learn Test

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  get: ^4.3.8
  #single local storage
  shared_preferences: ^2.0.5
  #cached image with loading indicator and error widget
  cached_network_image: ^3.1.0
  #auto size text
  auto_size_text: ^3.0.0
  #size based on design draft
  flutter_screenutil: ^5.0.0+2
  #load svg image
  flutter_svg: ^0.23.0+1
  intl: ^0.17.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/kukelola_logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-UltraBold.ttf
          weight: 800
        - asset: assets/fonts/Merriweather-Bold.ttf
          weight: 700
        - asset: assets/fonts/Merriweather-Regular.ttf
          weight: 400
        - asset: assets/fonts/Merriweather-Light.ttf
          weight: 300
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100